"""add_detailed_activity_fields

Revision ID: 6200e2283c33
Revises: 7ac4c0e817d8
Create Date: 2026-04-27 14:27:41.327527
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6200e2283c33'
down_revision: Union[str, None] = '7ac4c0e817d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('module', sa.String(length=100), nullable=True))
    op.add_column('activity_logs', sa.Column('before_state', sa.Text(), nullable=True))
    op.add_column('activity_logs', sa.Column('after_state', sa.Text(), nullable=True))
    op.add_column('activity_logs', sa.Column('target_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'target_link')
    op.drop_column('activity_logs', 'after_state')
    op.drop_column('activity_logs', 'before_state')
    op.drop_column('activity_logs', 'module')
    # ### end Alembic commands ###
