"""Add project_preferences table

Revision ID: 873a5c1e1cda
Revises: cc3f636798f6
Create Date: 2026-04-15 10:17:26.456903
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873a5c1e1cda'
down_revision: Union[str, None] = 'cc3f636798f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_preferences',
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('config_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_preferences')
    # ### end Alembic commands ###
