"""add_cerberus_auth_logs

Revision ID: 7ac4c0e817d8
Revises: dc81e5563523
Create Date: 2026-04-27 12:22:03.215109
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac4c0e817d8'
down_revision: Union[str, None] = 'dc81e5563523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cerberus_auth_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cerberus_auth_logs_email'), 'cerberus_auth_logs', ['email'], unique=False)
    op.create_index(op.f('ix_cerberus_auth_logs_timestamp'), 'cerberus_auth_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cerberus_auth_logs_timestamp'), table_name='cerberus_auth_logs')
    op.drop_index(op.f('ix_cerberus_auth_logs_email'), table_name='cerberus_auth_logs')
    op.drop_table('cerberus_auth_logs')
    # ### end Alembic commands ###
